### ISSUE TITLE
git permission denied

### ISSUE THREAD

**Issue by DipFlip** [ess-dmsc/essdaq#6]
When install.sh ran 
`git clone git@github.com:ess-dmsc/daquiri.git`

I got the following:

> Cloning into 'daquiri'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

But running `git clone https://github.com/ess-dmsc/daquiri.git` worked fine. Just thought you might want to know.

Cheers!

**Comment by zjttoefs** [comment]
The logic to find out whether to use ssh or https may be broken.

If you comment out this line in install.sh: 
``. ./config/sshconfig.sh``
with a # in front of it. You should be getting further.
