### ISSUE TITLE
MTU configuration script

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/essdaq#8]
To quote your email to Doro:

```
So, at least on my Ubuntu you can make these permanent
by appending the following lines to /etc/sysctl.conf
 
net.core.rmem_max = 12582912
net.core.wmem_max = 12582912
net.core.netdev_max_backlog = 5000
 
These will persist after reboot
 
If you dont want to reboot now can then also do
 
sudo sysctl -w net.core.rmem_max=12582912
etc.
```

Could we please make some scripts to make these changes and checks automatic so that we have some idea of these problems even before the EFU fails in some new and exotic way? ;)

**Comment by mortenjc** [comment]
Yes, but they are not fail safe. I created one called hwcheck.sh last week for multiblade which is already in the repo. Since names of ethernet ports change on different systems this script may need to be tweaked for each system.

**Comment by mortenjc** [comment]
But actually these checks are done in the efu at boot and we only missed them because all output was redirected to a log file.

**Comment by mortenjc** [comment]
If you come to the office next week we should discuss the latest lessons learned and talk about what we want to move from event-formation-unit to essdaq, etc...

**Comment by martukas** [comment]
> But actually these checks are done in the efu at boot and we only missed them because all output was redirected to a log file.

Well, my approach to it was: write to file and then watch the file with glogg, for which thee is a script under `efu/watch_log.sh` But what is the correct way to do this then? The logger actually should write to file with filestamps, according to Jonas, so what we should be doing is have a cmd parameter to write that to a predictable/accessible location and then monitor it with something like glogg.

**Comment by mortenjc** [comment]
I have improved the essdaq scripts so this should now be improved.

**Comment by mortenjc** [comment]
I meant 'updated the essdaq scripts, so ...'
